criado class e metodos GerenciadorClientes.java. resolved #830
marcosdosea/gcm-ufs pull request #833
Opened 2022-07-29 13:25 UTC by ms-daniel

preciso da revisão urgentemente.

2022-07-30 14:20 UTC, viniVN7 requested changes
Bom dia, Carlos. Tudo certo?
Acabei de revisar seu código referente a issue #830. Abaixo estão minhas observações:
É preciso manter um padrão quanto ao nome dos atributos. Deste modo, recomendo a alteração do nome dos atributos "nomeC" e "idadeC". Uma vez que, como estão na classe GerenciadorCliente, pode-se declarar as mesmas apenas como "nome" e "idade". 
Por fim, no retorno do "else", no método "consultarCliente", é mais interessante apresentar uma mensagem mais clara para o usuário. Por exemplo: "O cliente X não foi encontrado", "Não há informações sobre o cliente X no sistema".

2022-07-31 13:42 UTC, viniVN7 approved these changes
Bom dia, Daniel.
Código revisado e aprovado!

2022-07-31 13:59 UTC, ms-daniel commented
solicito o merge e exclusão da branch!

2022-07-31 14:03 UTC, merged

2022-07-31 14:05 UTC, viniVN7 commented
Merge aprovado e branch excluído!